/* TC-179 escenario 2 — las guardas de ambiguedad del enlace por item del credito.
   Sonda de solo lectura. Reproduce las condiciones del OUTER APPLY del PR y cuenta,
   por separado, los casos que CADA guarda excluye. */
SELECT
    'total_lineas_standard_sin_origen' AS metric,
    COUNT(*) AS n
FROM FINANCIALTRANSACTIONLINEITEM rli
INNER JOIN FINANCIALTRANSACTION ft ON ft.ID = rli.FINANCIALTRANSACTIONID AND ft.[TYPE] = 'Refund'
WHERE rli.[TYPE] = 'Standard' AND rli.SOURCELINEITEMID IS NULL

UNION ALL
SELECT
    'guarda1_credito_con_item_hermano',
    COUNT(*)
FROM FINANCIALTRANSACTIONLINEITEM rli
INNER JOIN FINANCIALTRANSACTION ft ON ft.ID = rli.FINANCIALTRANSACTIONID AND ft.[TYPE] = 'Refund'
WHERE rli.[TYPE] = 'Standard' AND rli.SOURCELINEITEMID IS NULL
  AND EXISTS (
        SELECT 1 FROM CREDITITEM ci
        INNER JOIN SALESORDERITEMMEMBERSHIP soim
            ON soim.ID = ci.SALESORDERITEMID AND soim.MEMBERSHIPTRANSACTIONID IS NULL
        WHERE ci.CREDITID = ft.ID)
  AND (SELECT COUNT(*) FROM CREDITITEM c2 WHERE c2.CREDITID = ft.ID) > 1

UNION ALL
SELECT
    'guarda2_reembolso_con_dos_lineas_sin_origen',
    COUNT(*)
FROM FINANCIALTRANSACTIONLINEITEM rli
INNER JOIN FINANCIALTRANSACTION ft ON ft.ID = rli.FINANCIALTRANSACTIONID AND ft.[TYPE] = 'Refund'
WHERE rli.[TYPE] = 'Standard' AND rli.SOURCELINEITEMID IS NULL
  AND (SELECT COUNT(*) FROM FINANCIALTRANSACTIONLINEITEM s2
       WHERE s2.FINANCIALTRANSACTIONID = ft.ID AND s2.[TYPE] = 'Standard' AND s2.SOURCELINEITEMID IS NULL) > 1

UNION ALL
SELECT
    'item_unico_pero_no_membresia_respaldada_por_orden',
    COUNT(*)
FROM FINANCIALTRANSACTIONLINEITEM rli
INNER JOIN FINANCIALTRANSACTION ft ON ft.ID = rli.FINANCIALTRANSACTIONID AND ft.[TYPE] = 'Refund'
WHERE rli.[TYPE] = 'Standard' AND rli.SOURCELINEITEMID IS NULL
  AND (SELECT COUNT(*) FROM CREDITITEM c2 WHERE c2.CREDITID = ft.ID) = 1
  AND NOT EXISTS (
        SELECT 1 FROM CREDITITEM ci
        INNER JOIN SALESORDERITEMMEMBERSHIP soim
            ON soim.ID = ci.SALESORDERITEMID AND soim.MEMBERSHIPTRANSACTIONID IS NULL
        WHERE ci.CREDITID = ft.ID)

UNION ALL
SELECT
    'admitidas_por_la_rama_del_item_del_credito',
    COUNT(*)
FROM FINANCIALTRANSACTIONLINEITEM rli
INNER JOIN FINANCIALTRANSACTION ft ON ft.ID = rli.FINANCIALTRANSACTIONID AND ft.[TYPE] = 'Refund'
WHERE rli.[TYPE] = 'Standard' AND rli.SOURCELINEITEMID IS NULL
  AND (SELECT COUNT(*) FROM CREDITITEM c2 WHERE c2.CREDITID = ft.ID) = 1
  AND (SELECT COUNT(*) FROM FINANCIALTRANSACTIONLINEITEM s2
       WHERE s2.FINANCIALTRANSACTIONID = ft.ID AND s2.[TYPE] = 'Standard' AND s2.SOURCELINEITEMID IS NULL) = 1
  AND EXISTS (
        SELECT 1 FROM CREDITITEM ci
        INNER JOIN SALESORDERITEMMEMBERSHIP soim
            ON soim.ID = ci.SALESORDERITEMID AND soim.MEMBERSHIPTRANSACTIONID IS NULL
        WHERE ci.CREDITID = ft.ID)

UNION ALL
SELECT
    'lineas_discount_con_linea_standard_hermana_no_admitidas',
    COUNT(*)
FROM FINANCIALTRANSACTIONLINEITEM rli
INNER JOIN FINANCIALTRANSACTION ft ON ft.ID = rli.FINANCIALTRANSACTIONID AND ft.[TYPE] = 'Refund'
WHERE rli.[TYPE] = 'Discount' AND rli.SOURCELINEITEMID IS NOT NULL
  AND EXISTS (SELECT 1 FROM FINANCIALTRANSACTIONLINEITEM sl
              WHERE sl.FINANCIALTRANSACTIONID = ft.ID AND sl.[TYPE] = 'Standard')

UNION ALL
SELECT
    'lineas_discount_sin_linea_standard_admitidas',
    COUNT(*)
FROM FINANCIALTRANSACTIONLINEITEM rli
INNER JOIN FINANCIALTRANSACTION ft ON ft.ID = rli.FINANCIALTRANSACTIONID AND ft.[TYPE] = 'Refund'
WHERE rli.[TYPE] = 'Discount' AND rli.SOURCELINEITEMID IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM FINANCIALTRANSACTIONLINEITEM sl
                  WHERE sl.FINANCIALTRANSACTIONID = ft.ID AND sl.[TYPE] = 'Standard');
