schemaVersion: '1.0'
project:
  name: TestManager Retooling
  prefix: TC
  counters:
    testCase: 57
    testSuite: 0
    testPlan: 14
    testRun: 65
  settings: null
  defaultPriority: medium
  defaultType: functional
  requireApproval: false
  attachmentsMaxSizeMb: 10
