SELECT
    CAST(rmg.ID AS VARCHAR(36))                AS ClaimId,
    CAST(rmg.MGSOURCEREVENUEID AS VARCHAR(36)) AS DonorId,
    mg.TYPECODE                                AS ClaimTypeCode,
    CAST(mg.CALCULATEDDATE AS DATE)            AS ClaimDate,
    donor_ft.TYPECODE                          AS DonorTypeCode,
    CAST(donor_ft.CALCULATEDDATE AS DATE)      AS DonorDate,
    CASE WHEN EXISTS (
        SELECT 1 FROM SALESORDERPAYMENT sop WHERE sop.PAYMENTID = rmg.MGSOURCEREVENUEID
    ) THEN 1 ELSE 0 END                        AS DonorIsOrderPayment,
    CASE WHEN EXISTS (
        SELECT 1
        FROM FINANCIALTRANSACTIONLINEITEM dli
        INNER JOIN MEMBERSHIPTRANSACTION mt
            ON mt.REVENUESPLITID = dli.ID OR mt.REVENUESPLITID = dli.SOURCELINEITEMID
        WHERE dli.FINANCIALTRANSACTIONID = rmg.MGSOURCEREVENUEID
          AND dli.[TYPE] = 'Standard'
    ) THEN 1 ELSE 0 END                        AS DonorIsMembershipPayment,
    CASE WHEN EXISTS (
        SELECT 1
        FROM FINANCIALTRANSACTIONLINEITEM dli
        INNER JOIN FINANCIALTRANSACTIONLINEITEM src ON src.ID = dli.SOURCELINEITEMID
        INNER JOIN FINANCIALTRANSACTION fp ON fp.ID = src.FINANCIALTRANSACTIONID AND fp.TYPECODE = 1
        WHERE dli.FINANCIALTRANSACTIONID = rmg.MGSOURCEREVENUEID
    ) THEN 1 ELSE 0 END                        AS DonorIsPledgePayment
FROM REVENUEMATCHINGGIFT rmg
INNER JOIN FINANCIALTRANSACTION mg ON mg.ID = rmg.ID
LEFT JOIN FINANCIALTRANSACTION donor_ft ON donor_ft.ID = rmg.MGSOURCEREVENUEID
WHERE rmg.ISACTIVE = 1;
