SELECT
  (SELECT COUNT(*) FROM RESERVATION) AS reservations,
  (SELECT COUNT(*) FROM SALESORDERITEMTAX t INNER JOIN SALESORDERITEM soi ON soi.ID = t.SALESORDERITEMID INNER JOIN RESERVATION r ON r.ID = soi.SALESORDERID) AS rental_tax_rows,
  (SELECT COUNT(*) FROM (SELECT t.SALESORDERITEMID FROM SALESORDERITEMTAX t INNER JOIN SALESORDERITEM soi ON soi.ID = t.SALESORDERITEMID INNER JOIN RESERVATION r ON r.ID = soi.SALESORDERID GROUP BY t.SALESORDERITEMID HAVING COUNT(*) > 1) x) AS rental_items_multi_tax;
