SELECT m.STATUSCODE AS codigo, m.STATUS AS estado, COUNT_BIG(1) AS membresias,
       SUM(CASE WHEN m.EXPIRATIONDATE IS NULL THEN 1 ELSE 0 END) AS sin_expiracion
FROM MEMBERSHIP m
GROUP BY m.STATUSCODE, m.STATUS
ORDER BY m.STATUSCODE;
